typography_spectrum: 0.5050483669620007
color:
  brandStrength: 0.887372539145872
  lightness: 0.23286549421027303
  saturation: 0.788898783037439
  rhythmicContrast: 0.8346637182403356
  brandColors:
    - '#010101'
    - '#B1B0AB'
    - '#F2EEEB'
    - '#736987'
    - '#383643'
opengraph:
  appId: '574667839304032'
  type: Apps for Pages
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3ca78438-e0eb-49b4-967d-bc2b62ae5724.png
layout_spectrum: 0.3602106769103557
author:
  name: Bianca Mauro
  email: bianca@thegrownupproject.org
  url: www.thegrownupproject.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2896551e-94f4-4f67-bd98-9b1bd04c4144.png
name: The GrownUp Project
title: The GrownUp Project
description: rediscover your happy
