typography_spectrum: 0.9965592557564378
color:
  brandStrength: 0.9734191768802702
  lightness: 0.7470371199306101
  saturation: 0.1201872827950865
  rhythmicContrast: 0.018880814546719193
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.5438818328548223
author:
  name: Bianca Mauro
  email: bianca@thegrownupproject.org
  url: www.thegrownupproject.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2896551e-94f4-4f67-bd98-9b1bd04c4144.png
name: The GrownUp Project
title: rediscover your happy
description: rediscover your happy
